name: "iCloud Backup App"
description: "Upload your backups to iCloud Drive"
version: "2026.02.1"
image: ghcr.io/fabiann2205/{arch}-icloud-backup-app
slug: "icloud_backup"
init: false
url: https://github.com/Fabiann2205/iCloud-Backup-App
arch:
  - aarch64
  - amd64
startup: application
hassio_role: backup
hassio_api: true
map:
  - type: backup
    read_only: false
options:
  username: null
  password: null
  icloud_directory_name: "Home Assistant Backups"
  delete_local_backups_after_upload: false
schema:
  username: email
  password: password
  icloud_directory_name: str
  delete_local_backups_after_upload: bool
apparmor: true
ingress: true
ingress_port: 5000
panel_icon: mdi:apple-icloud
panel_title: "iCloud Backup"
panel_admin: false
